// Witness-generation test for the three AMM circuits.
//
// For each circuit, build a sample input using the reference impl in
// tests/amm-* and confirm the wasm witness calculator can produce a valid
// witness. Witness-generation failure = constraint violation, so this is
// effectively a satisfiability test for the circuit + reference-impl pair.
//
// Run from this directory: `node witness-test.mjs`
// (Requires build/ artifacts; run ./build.sh first.)

import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, resolve } from 'path';
import { createRequire } from 'module';

const __dirname = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);

// Reference impl is in tests/. Import via absolute paths.
const TESTS_DIR = resolve(__dirname, '../../../tests');

// Use the WitnessCalculator generated by circom. circom emits the calculator
// as CommonJS (`module.exports = ...`); load it via createRequire so the
// embedded wasm-bindings function works in our ES-module context.
async function buildWitnessCalculator(name) {
  // build.sh copies witness_calculator.js → witness_calculator.cjs so we can
  // require it from this ES-module file (parent package sets "type":"module").
  const wcFactory = require(resolve(__dirname, `build/${name}_js/witness_calculator.cjs`));
  const wasm = readFileSync(resolve(__dirname, `build/${name}_js/${name}.wasm`));
  return await wcFactory(wasm);
}

let pass = 0, fail = 0;
function test(label, fn) {
  return fn().then(
    (ok) => {
      if (ok) { console.log(`  PASS  ${label}`); pass++; }
      else    { console.log(`  FAIL  ${label}`); fail++; }
    },
    (e) => { console.log(`  THROW ${label}: ${e.message}`); fail++; }
  );
}

// ---- Reference primitives (lazy import to avoid load-time path issues) ----
const bjj      = await import(resolve(TESTS_DIR, 'amm-bjj.mjs'));
const clearing = await import(resolve(TESTS_DIR, 'amm-clearing.mjs'));

function randomBJJBlinding() {
  while (true) {
    const buf = crypto.getRandomValues(new Uint8Array(32));
    let n = 0n;
    for (let i = 0; i < 32; i++) n = (n << 8n) | BigInt(buf[i]);
    if (n > 0n && n < bjj.N_BJJ) return n;
  }
}

// ---- Test 1: amm_lp_add witness ----
console.log('amm_lp_add witness generation');

await test('honest LP_ADD witness generates', async () => {
  const wc = await buildWitnessCalculator('amm_lp_add');

  const shareAmount = 1_414_213n;
  const r_share_BJJ = randomBJJBlinding();
  const C_share = bjj.pedersenBJJ(shareAmount, r_share_BJJ);

  const input = {
    pool_id_fr: '12345678901234567890',
    variant: '0',
    share_amount: shareAmount.toString(),
    C_share_BJJ_u: C_share[0].toString(),
    C_share_BJJ_v: C_share[1].toString(),
    r_share_BJJ: r_share_BJJ.toString(),
  };

  const witness = await wc.calculateWitness(input, true);
  return witness && witness.length > 0;
});

await test('tampered share commitment fails', async () => {
  const wc = await buildWitnessCalculator('amm_lp_add');
  const shareAmount = 1_414_213n;
  const r_share_BJJ = randomBJJBlinding();
  const C_share = bjj.pedersenBJJ(shareAmount, r_share_BJJ);
  // Lie about the amount but keep the same commitment u/v.
  const input = {
    pool_id_fr: '12345678901234567890',
    variant: '0',
    share_amount: (shareAmount + 1n).toString(),  // bumped, doesn't match commitment
    C_share_BJJ_u: C_share[0].toString(),
    C_share_BJJ_v: C_share[1].toString(),
    r_share_BJJ: r_share_BJJ.toString(),
  };
  try { await wc.calculateWitness(input, true); return false; }
  catch (e) { return /Assert Failed|Error in template/.test(e.message); }
});

// ---- Test 2: amm_lp_remove witness ----
console.log('\namm_lp_remove witness generation');

await test('honest LP_REMOVE witness generates', async () => {
  const wc = await buildWitnessCalculator('amm_lp_remove');

  const shareAmount = 1000n;
  const deltaA = 500n, deltaB = 1000n;
  const r_recv_A = randomBJJBlinding();
  const r_recv_B = randomBJJBlinding();
  const C_recv_A = bjj.pedersenBJJ(deltaA, r_recv_A);
  const C_recv_B = bjj.pedersenBJJ(deltaB, r_recv_B);

  const input = {
    pool_id_fr: '12345678901234567890',
    share_amount: shareAmount.toString(),
    delta_A: deltaA.toString(),
    delta_B: deltaB.toString(),
    recv_A_BJJ_u: C_recv_A[0].toString(),
    recv_A_BJJ_v: C_recv_A[1].toString(),
    recv_B_BJJ_u: C_recv_B[0].toString(),
    recv_B_BJJ_v: C_recv_B[1].toString(),
    r_recv_A_BJJ: r_recv_A.toString(),
    r_recv_B_BJJ: r_recv_B.toString(),
  };
  const witness = await wc.calculateWitness(input, true);
  return witness && witness.length > 0;
});

await test('LP_REMOVE with mismatched receipt fails', async () => {
  const wc = await buildWitnessCalculator('amm_lp_remove');
  const shareAmount = 1000n;
  const deltaA = 500n, deltaB = 1000n;
  const r_recv_A = randomBJJBlinding();
  const r_recv_B = randomBJJBlinding();
  const C_recv_A = bjj.pedersenBJJ(deltaA, r_recv_A);
  const C_recv_B = bjj.pedersenBJJ(deltaB, r_recv_B);
  // Swap u/v on one receipt — commitment now invalid.
  const input = {
    pool_id_fr: '12345678901234567890',
    share_amount: shareAmount.toString(),
    delta_A: deltaA.toString(),
    delta_B: deltaB.toString(),
    recv_A_BJJ_u: C_recv_A[1].toString(),  // swapped
    recv_A_BJJ_v: C_recv_A[0].toString(),
    recv_B_BJJ_u: C_recv_B[0].toString(),
    recv_B_BJJ_v: C_recv_B[1].toString(),
    r_recv_A_BJJ: r_recv_A.toString(),
    r_recv_B_BJJ: r_recv_B.toString(),
  };
  try { await wc.calculateWitness(input, true); return false; }
  catch (e) { return /Assert Failed|Error in template/.test(e.message); }
});

// ---- Test 3: amm_swap_batch witness (single trader for simplicity) ----
console.log('\namm_swap_batch witness generation (N=1 + 15 padding)');

const N_MAX = 16;
function buildSwapInput({ poolIdFr, R_A, R_B, fee_bps, traders }) {
  const X = traders.filter(t => t.direction === 0).reduce((s, t) => s + t.amount_in_swap, 0n);
  const Y = traders.filter(t => t.direction === 1).reduce((s, t) => s + t.amount_in_swap, 0n);
  const solve = clearing.solveClearing(X, Y, R_A, R_B, BigInt(fee_bps));

  // Per-trader amount_out + rem
  const filled = traders.map(t => {
    const aOut = clearing.amountOutForTrader(t.amount_in_swap, t.direction, solve.P_clear_num, solve.P_clear_den);
    let mult, div;
    if (t.direction === 0) { mult = solve.P_clear_den; div = solve.P_clear_num; }
    else                   { mult = solve.P_clear_num; div = solve.P_clear_den; }
    const num = t.amount_in_swap * mult;
    const rem = num - aOut * div;
    return { ...t, amount_out: aOut, rem };
  });

  // Aggregate tips per direction
  const tipA = filled.filter(t => t.direction === 0).reduce((s, t) => s + t.tip_amount, 0n);
  const tipB = filled.filter(t => t.direction === 1).reduce((s, t) => s + t.tip_amount, 0n);

  // Pad to N_MAX
  const direction = new Array(N_MAX).fill('0');
  const min_out = new Array(N_MAX).fill('0');
  const tip_amount = new Array(N_MAX).fill('0');
  const amount_in_swap = new Array(N_MAX).fill('0');
  const tip_amount_witness = new Array(N_MAX).fill('0');
  const r_in_BJJ = new Array(N_MAX).fill('0');
  const amount_out = new Array(N_MAX).fill('0');
  const rem = new Array(N_MAX).fill('0');
  const r_out_BJJ = new Array(N_MAX).fill('0');
  const C_in_BJJ_u = new Array(N_MAX).fill('0');
  const C_in_BJJ_v = new Array(N_MAX).fill('1');  // identity (0, 1)
  const C_out_BJJ_u = new Array(N_MAX).fill('0');
  const C_out_BJJ_v = new Array(N_MAX).fill('1');

  for (let i = 0; i < filled.length; i++) {
    const t = filled[i];
    const inTotal = t.amount_in_swap + t.tip_amount;
    const r_in = randomBJJBlinding();
    const r_out = randomBJJBlinding();
    const C_in = bjj.pedersenBJJ(inTotal, r_in);
    const C_out = bjj.pedersenBJJ(t.amount_out, r_out);

    direction[i] = t.direction.toString();
    min_out[i] = t.min_out.toString();
    tip_amount[i] = t.tip_amount.toString();
    amount_in_swap[i] = t.amount_in_swap.toString();
    tip_amount_witness[i] = t.tip_amount.toString();
    r_in_BJJ[i] = r_in.toString();
    amount_out[i] = t.amount_out.toString();
    rem[i] = t.rem.toString();
    r_out_BJJ[i] = r_out.toString();
    C_in_BJJ_u[i] = C_in[0].toString();
    C_in_BJJ_v[i] = C_in[1].toString();
    C_out_BJJ_u[i] = C_out[0].toString();
    C_out_BJJ_v[i] = C_out[1].toString();
  }

  // delta_A_net_signed: direction='A→B' → A flows in → positive; 'B→A' → negative.
  // For mixed batches, the signs come from the solve direction.
  let deltaA_sign = 0, deltaB_sign = 0;
  if (solve.direction === 'A→B') { deltaA_sign = 0; deltaB_sign = 1; }
  else if (solve.direction === 'B→A') { deltaA_sign = 1; deltaB_sign = 0; }

  return {
    pool_id_fr: poolIdFr,
    R_A_pre: R_A.toString(),
    R_B_pre: R_B.toString(),
    delta_A_net_sign: deltaA_sign.toString(),
    delta_A_net_magnitude: solve.delta_a_net.toString(),
    delta_B_net_sign: deltaB_sign.toString(),
    delta_B_net_magnitude: solve.delta_b_net.toString(),
    tip_A_amount: tipA.toString(),
    tip_B_amount: tipB.toString(),
    fee_bps: fee_bps.toString(),
    n_intents: filled.length.toString(),
    direction, C_in_BJJ_u, C_in_BJJ_v, min_out, tip_amount,
    C_out_BJJ_u, C_out_BJJ_v,
    amount_in_swap, tip_amount_witness, r_in_BJJ,
    amount_out, rem, r_out_BJJ,
  };
}

await test('honest single-trader A→B swap (N=1) generates', async () => {
  const wc = await buildWitnessCalculator('amm_swap_batch');
  const input = buildSwapInput({
    poolIdFr: '12345678901234567890',
    R_A: 1_000_000n, R_B: 2_000_000n, fee_bps: 30,
    traders: [{
      direction: 0,
      amount_in_swap: 1000n,
      tip_amount: 0n,
      min_out: 0n,
    }],
  });
  const witness = await wc.calculateWitness(input, true);
  return witness && witness.length > 0;
});

await test('honest single-trader B→A swap (N=1) generates', async () => {
  const wc = await buildWitnessCalculator('amm_swap_batch');
  const input = buildSwapInput({
    poolIdFr: '12345678901234567890',
    R_A: 1_000_000n, R_B: 2_000_000n, fee_bps: 30,
    traders: [{
      direction: 1,
      amount_in_swap: 1000n,
      tip_amount: 0n,
      min_out: 0n,
    }],
  });
  const witness = await wc.calculateWitness(input, true);
  return witness && witness.length > 0;
});

await test('two-trader swap (N=2) — one A→B, one B→A', async () => {
  const wc = await buildWitnessCalculator('amm_swap_batch');
  const input = buildSwapInput({
    poolIdFr: '12345678901234567890',
    R_A: 1_000_000n, R_B: 2_000_000n, fee_bps: 30,
    traders: [
      { direction: 0, amount_in_swap: 800n,  tip_amount: 10n, min_out: 0n },
      { direction: 1, amount_in_swap: 1000n, tip_amount: 20n, min_out: 0n },
    ],
  });
  const witness = await wc.calculateWitness(input, true);
  return witness && witness.length > 0;
});

await test('min_out violation fails witness generation', async () => {
  const wc = await buildWitnessCalculator('amm_swap_batch');
  const input = buildSwapInput({
    poolIdFr: '12345678901234567890',
    R_A: 1_000_000n, R_B: 2_000_000n, fee_bps: 30,
    traders: [{
      direction: 0, amount_in_swap: 1000n, tip_amount: 0n,
      min_out: 999_999_999n,  // impossible
    }],
  });
  try { await wc.calculateWitness(input, true); return false; }
  catch (e) { return /Assert Failed|Error in template/.test(e.message); }
});

await test('spot-clearing batch (perfectly balanced) generates', async () => {
  const wc = await buildWitnessCalculator('amm_swap_batch');
  // X=500 A→B, Y=1000 B→A on 1:2 pool. X·R_B = Y·R_A → spot batch.
  const input = buildSwapInput({
    poolIdFr: '12345678901234567890',
    R_A: 1_000_000n, R_B: 2_000_000n, fee_bps: 30,
    traders: [
      { direction: 0, amount_in_swap: 500n,  tip_amount: 0n, min_out: 0n },
      { direction: 1, amount_in_swap: 1000n, tip_amount: 0n, min_out: 0n },
    ],
  });
  const witness = await wc.calculateWitness(input, true);
  return witness && witness.length > 0;
});

console.log(`\n${pass}/${pass + fail} passed`);
if (fail > 0) process.exit(1);
