// Native (cargo test) coverage for the soundness-critical pieces of the guest's
// state model. These run on the host — excluded from the release ELF — so they
// add zero risk to the proven program while pinning behaviour the SP1 guest and
// the on-chain mixer both depend on.

use crate::merkle::{NullifierSet, PoseidonTree};
use crate::poseidon::hash2;

fn h(hex: &str) -> [u8; 32] {
    let mut out = [0u8; 32];
    for i in 0..32 {
        out[i] = u8::from_str_radix(&hex[2 * i..2 * i + 2], 16).unwrap();
    }
    out
}
fn be_u64(n: u64) -> [u8; 32] {
    let mut b = [0u8; 32];
    b[24..32].copy_from_slice(&n.to_be_bytes());
    b
}

// ── Poseidon parity ──────────────────────────────────────────────────────
// Reference values generated by circomlibjs buildPoseidon() — the same hash
// the dApp and the circom circuit use. If light-poseidon's new_circom(2) ever
// diverges, deposit leaves/roots computed off-chain would stop validating.

#[test]
fn poseidon_matches_circomlib_vectors() {
    assert_eq!(
        hash2(&be_u64(1), &be_u64(2)),
        h("115cc0f5e7d690413df64c6b9662e9cf2a3617f2743245519e19607a4417189a"),
        "poseidon2(1,2) parity"
    );
    assert_eq!(
        hash2(&be_u64(0), &be_u64(0)),
        h("2098f5fb9e239eab3ceac3f27b81e481dc3124d55ffed523a839ee8446b64864"),
        "poseidon2(0,0) parity"
    );
}

// ── Merkle tree ──────────────────────────────────────────────────────────

#[test]
fn empty_tree_root_matches_dapp_convention() {
    // zeros[0] = literal 0 (guest convention), folded depth 20.
    let t = PoseidonTree::new();
    assert_eq!(
        t.root(),
        h("2134e76ac5d21aab186c2be1dd8f84ee880a1e46eaf712f9d371b6df22191f3e"),
        "empty 20-level root"
    );
    assert_eq!(t.next_index(), 0);
}

#[test]
fn insert_advances_root_deterministically() {
    let mut a = PoseidonTree::new();
    let mut b = PoseidonTree::new();
    let r0 = a.root();
    for i in 0..7u64 {
        assert!(a.insert(be_u64(100 + i)));
        assert!(b.insert(be_u64(100 + i)));
    }
    assert_ne!(a.root(), r0, "root must change after inserts");
    assert_eq!(a.root(), b.root(), "same inserts → same root");
    assert_eq!(a.next_index(), 7);
}

#[test]
fn from_frontier_round_trips() {
    let mut t = PoseidonTree::new();
    for i in 0..5u64 {
        t.insert(be_u64(7 * i + 1));
    }
    let (frontier, idx, root) = (t.frontier(), t.next_index(), t.root());
    // Reconstruct and continue inserting; must track a freshly-built tree.
    let mut rebuilt = PoseidonTree::from_frontier(frontier, idx, root);
    assert_eq!(rebuilt.root(), root);
    let mut reference = PoseidonTree::new();
    for i in 0..5u64 {
        reference.insert(be_u64(7 * i + 1));
    }
    rebuilt.insert(be_u64(999));
    reference.insert(be_u64(999));
    assert_eq!(rebuilt.root(), reference.root(), "reconstructed tree diverged");
}

#[test]
#[should_panic(expected = "frontier does not match claimed root")]
fn from_frontier_rejects_wrong_root() {
    let mut t = PoseidonTree::new();
    for i in 0..4u64 {
        t.insert(be_u64(i + 1));
    }
    let mut bad_root = t.root();
    bad_root[31] ^= 1;
    PoseidonTree::from_frontier(t.frontier(), t.next_index(), bad_root);
}

#[test]
#[should_panic(expected = "frontier does not match claimed root")]
fn from_frontier_rejects_tampered_frontier() {
    // next_index = 5 (binary 101) so frontier[0] is consumed by the root
    // recomputation; tampering it must be caught. (Entries at unset index bits
    // are not used for the current root — they remain pinned by the outer
    // state-commitment hash chain in the guest, see SP1PoolRootVerifier.)
    let mut t = PoseidonTree::new();
    for i in 0..5u64 {
        t.insert(be_u64(i + 1));
    }
    let mut f = t.frontier();
    f[0][0] ^= 1;
    PoseidonTree::from_frontier(f, t.next_index(), t.root());
}

#[test]
#[should_panic(expected = "mismatch")]
fn from_frontier_rejects_fake_empty() {
    let z = [0u8; 32];
    PoseidonTree::from_frontier([z; 20], 0, [1u8; 32]);
}

// ── NullifierSet ─────────────────────────────────────────────────────────

#[test]
fn nullifier_set_blocks_double_spend() {
    let mut s = NullifierSet::new();
    let n = be_u64(42);
    assert!(s.insert(n), "first spend ok");
    assert!(!s.insert(n), "in-batch double-spend rejected");
    s.finalize();
    // Cross-batch: reconstruct from the sorted history, same nullifier rejected.
    let hash = s.hash();
    let mut s2 = NullifierSet::from_sorted(vec![n]);
    assert!(!s2.insert(n), "cross-batch double-spend rejected");
    // Reconstructing from the same sorted set reproduces the same hash.
    let mut s3 = NullifierSet::from_sorted(vec![n]);
    s3.finalize();
    assert_eq!(s3.hash(), hash, "hash not reproducible from sorted history");
}

#[test]
fn nullifier_empty_hash_is_zero() {
    let s = NullifierSet::new();
    assert_eq!(s.hash(), [0u8; 32]);
}

#[test]
fn nullifier_hash_order_independent_of_insertion() {
    let (a, b, c) = (be_u64(3), be_u64(1), be_u64(2));
    let mut s1 = NullifierSet::new();
    s1.insert(a); s1.insert(b); s1.insert(c);
    s1.finalize();
    let mut s2 = NullifierSet::new();
    s2.insert(c); s2.insert(a); s2.insert(b);
    s2.finalize();
    assert_eq!(s1.hash(), s2.hash(), "hash must be insertion-order independent");
    assert_eq!(s1.count(), 3);
}

#[test]
#[should_panic(expected = "must be sorted and unique")]
fn from_sorted_rejects_unsorted() {
    NullifierSet::from_sorted(vec![be_u64(5), be_u64(2)]);
}

#[test]
#[should_panic(expected = "must be sorted and unique")]
fn from_sorted_rejects_duplicate() {
    NullifierSet::from_sorted(vec![be_u64(5), be_u64(5)]);
}
